### ISSUE TITLE
pre-commit installation fails due to distutils import

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/geoutils#428]
**Describe the bug**

Using a 'clean' dev environment:

```bash
pre-commit run --all-files

[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/bin/python', '-mpip', 'install', '.', 'tokenize-rt==3.2.0', 'numpy==1.24')
return code: 2
stdout:
    Processing /Users/tedstona/.cache/pre-commit/repob4x5g7qf
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting tokenize-rt==3.2.0
      Using cached tokenize_rt-3.2.0-py2.py3-none-any.whl (6.1 kB)
    Collecting numpy==1.24
      Using cached numpy-1.24.0.tar.gz (10.9 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
        requirement_set = resolver.resolve(
                          ^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
        result = self._result = resolver.resolve(
                                ^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
        self._add_to_criteria(self.state.criteria, r, parent=None)
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
        if not criterion.candidates:
               ^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
        return bool(self._sequence)
               ^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
        return any(self)
               ^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
        return (c for c in iterator if id(c) not in self._incompatible_ids)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
        candidate = func()
                    ^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
        base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
        self._link_candidate_cache[link] = LinkCandidate(
                                           ^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
        super().__init__(
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
        self.dist = self._prepare()
                    ^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
        dist = self._prepare_distribution()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
        return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
        dist = _get_prepared_distribution(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
        abstract_dist.prepare_distribution_metadata(
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
        self._install_build_reqs(finder)
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
        build_reqs = self._get_build_requires_wheel()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
        return backend.get_requires_for_build_wheel()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 751, in get_requires_for_build_wheel
        return super().get_requires_for_build_wheel(config_settings=cs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
        return self._call_hook('get_requires_for_build_wheel', {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
        raise BackendUnavailable(data.get('traceback', ''))
    pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
      File "/Users/tedstona/.cache/pre-commit/repob4x5g7qf/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
        obj = import_module(mod_path)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tedstona/micromamba/envs/geoutils_dev/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 994, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/private/var/folders/r1/slqbzl397437r46552_t7115076fxg/T/pip-build-env-uh0lwf04/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
        import distutils.core
    ModuleNotFoundError: No module named 'distutils'
```

**To Reproduce**

Use the `.pre-commit-config.yaml` file in the repo. In the example above, I increased mypy-mirror version from 1.1.1 to 1.8.0 and increased numpy from 1.22 to 1.24, these did not fix the issue.

**Expected behavior**

pre-commit should pass.

**System (please complete the following information):**
 - OS: Mac
 - Environment micromamba with dev-environment.ml

**Comment by rhugonnet** [comment]
Mmhh... this is also a local issue, CI `pre-commit` is passing. You're finding hard issues @atedstone!

I see two possibilites you can try:
1. Your `conda`/`mamba` base environment needs to be updated: I've had `pre-commit` fail on some versions in the past, but it's been more stable recently.
2. I've seen the `distutils` error triggered elsewhere by Python 3.12. Maybe adding the max Python version in `environment.yml` file like this: ```python >=3.9, <3.12``` will fix your issue when creating the clean environment.

**Comment by rhugonnet** [comment]
If 2 is the limiting one, then we should PR that change into the package.

**Comment by atedstone** [comment]
My mamba base environment was freshly installed last week, so I tried out option 2 instead - limiting python<3.12. This allows `pre-commit  run --all-files` to complete the installation, but then I get more than 100 failures from `mypy`, snip of head of output:

```python
geoutils/projtools.py:281: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[Any]]", variable has type "tuple[list[float], list[float]]")  [assignment]
geoutils/projtools.py:298: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[Any]]", variable has type "tuple[list[float], list[float]]")  [assignment]
geoutils/vector.py:1343: error: Incompatible types in assignment (expression has type "Raster", variable has type "Mask")  [assignment]
geoutils/raster/raster.py:2512: error: Incompatible types in assignment (expression has type "floating[Any] | integer[Any]", variable has type "float | int | None")  [assignment]
geoutils/raster/raster.py:2515: error: Incompatible types in assignment (expression has type "floating[Any] | integer[Any]", variable has type "float | int | None")  [assignment]
geoutils/raster/raster.py:2519: error: Argument 1 to "float" has incompatible type "float | int | None"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
geoutils/raster/raster.py:2520: error: Argument 1 to "float" has incompatible type "float | int | None"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
geoutils/raster/multiraster.py:70: error: Incompatible return value type (got "list[Raster]", expected "list[RasterType]")  [return-value]
geoutils/raster/multiraster.py:109: error: Incompatible return value type (got "list[Raster]", expected "list[RasterType]")  [return-value]
...
Found 120 errors in 8 files (checked 23 source files)
```

**Comment by rhugonnet** [comment]
OK good that `pre-commit` re-runs now at least!
For mypy: Do you still have the upgraded version in `.pre-commit-config.yaml` that you mentioned above (to try to solve the issue in your first comment)?
If yes, downgrading back to the one in the repo should solve it! (they always add new default rules in mypy, so upgrading often breaks the typing check :sweat_smile:)

**Comment by atedstone** [comment]
Good spot - that was exactly the problem. I'll open a PR to keep python<3.12 in the dev environment when I get a moment.
