### ISSUE TITLE
Raster class CRS object is invalid for some reason

### ISSUE THREAD

**Issue by eriksholmlund** [GlacioHack/GeoUtils#61]
I have a weird CRS issue with using Vectors and Rasters together:

I am trying to use the Vector `exclusion_mask` to create a mask for the Raster `reference_raster`:
```python
mask_array = exclusion_mask.create_mask(reference_raster, crs=reference_raster.crs)
```
but this raises an error:
```bash
Traceback (most recent call last):                                                                                                                         
  File "/home/erik/Projects/ETH/GlacioHack/DemUtils/DemUtils/coreg.py", line 703, in <module>                                                              
    test_icp_coregistration()                                                                                                                              
  File "/home/erik/Projects/ETH/GlacioHack/DemUtils/DemUtils/coreg.py", line 683, in test_icp_coregistration                                               
    aligned_raster, error = coregistration.run(reference_raster, to_be_aligned_raster, glacier_mask)                                                       
  File "/home/erik/Projects/ETH/GlacioHack/DemUtils/DemUtils/coreg.py", line 654, in run                                                                   
    mask_array = exclusion_mask.create_mask(reference_raster, crs=reference_raster.crs)                                                                    
  File "/home/erik/.local/share/conda/demutils/lib/python3.9/site-packages/geoutils/geovector.py", line 151, in create_mask                                
    vect = self.ds.to_crs(crs)                                                                                                                             
  File "/home/erik/.local/share/conda/demutils/lib/python3.9/site-packages/geopandas/geodataframe.py", line 816, in to_crs                                 
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)                                                                                                          
  File "/home/erik/.local/share/conda/demutils/lib/python3.9/site-packages/geopandas/geoseries.py", line 541, in to_crs                                    
    transformer = Transformer.from_crs(self.crs, crs, always_xy=True)                                                                                      
  File "/home/erik/.local/share/conda/demutils/lib/python3.9/site-packages/pyproj/transformer.py", line 368, in from_crs                                   
    _Transformer.from_crs(                                                                                                                                 
  File "pyproj/_transformer.pyx", line 349, in pyproj._transformer._Transformer.from_crs                                                                   
pyproj.exceptions.ProjError: Error creating Transformer from CRS
```

I have found a workaround which is very ugly but might aid in debugging:
```python
# Extract the string version of the CRS
crs_string = reference_raster.crs.__repr__()
# Find the last EPSG entry (assuming there is one..)
crs_epsg = crs_string[crs_string.rindex("EPSG") + 7: crs_string.rindex("\"]]")]

reference_raster.crs = pyproj.crs.CRS.from_epsg(crs_epsg)

# Now this works
mask_array = exclusion_mask.create_mask(reference_raster)
```

The Vector CRS is ETRS89 UTM 33N and the Raster CRS is WGS84 UTM 33N

**Comment by adehecq** [comment]
Looks like an issue in geopandas, rather than geoutils. I'll have a closer look.

**Comment by adehecq** [comment]
Also your fix might be incorrect. In the WKT projection string, there are usually several EPSG codes, which do not correspond to your projection's EPSG. But you should have a method proj.to_epsg to get your actual EPSG code if it exists.

**Comment by eriksholmlund** [comment]
@adehecq I saw that there were multiple EPSG codes, but noticed that the last one corresponds to the actual one, hence my use of `.rindex()`.

I tried `print(reference_raster.crs.to_epsg())` which gave `None` as a result. I think the Raster's CRS object is off somehow...

**Comment by adehecq** [comment]
Yes, my guess is that the CRS is wrong for that raster... Especially if modifying the raster's CRS fixes the issue. Can you pritn the proj4 of the projection before and after the fix?

**Comment by eriksholmlund** [comment]
`reference_raster.crs.to_proj4()` returns an empty string before fixing. After fixing, it returns `+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs +type=crs`.

`reference_raster.crs.__repr__()` before fixing:
```bash
CRS.from_wkt('LOCAL_CS["ETRS89 / UTM zone 33N",UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","25833"]]')
```

after fixing:
```bash
<Projected CRS: EPSG:25833>
Name: ETRS89 / UTM zone 33N                                                                                                                                
Axis Info [cartesian]:                                                                                                                                     
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Europe between 12°E and 18°E: Austria; Denmark - offshore and offshore; Germany - onshore and offshore; Norway including Svalbard - onshore and offshore.
- bounds: (12.0, 46.4, 18.01, 84.01)
Coordinate Operation:
- name: UTM zone 33N
- method: Transverse Mercator
Datum: European Terrestrial Reference System 1989
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```

Looks like the CRS object is instantiated incorrectly. Is GeoUtils modifying the CRS at all?

My pyproj version is 3.0.0.post1 by the way.

**Comment by eriksholmlund** [comment]
Sorry @adehecq for wasting your time.. I upgraded `proj` from `7.1.2` to `7.2.2` and now it's working without the fix!
